#!/usr/bin/env python3
"""
Fix v2: Baut msapp ohne YAML-Controls (nur Controls-JSON).
Screens werden mit echten Controls-JSON-Kindknoten befüllt.
Die pa.yaml Dateien werden MINIMAL gehalten (nur Theme) um Parser-Fehler zu vermeiden.
"""

import zipfile, io, os, json

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
SOLUTION_IN   = os.path.join(SCRIPT_DIR, "Petra_1_0_0_0.zip")
SOLUTION_OUT  = os.path.join(SCRIPT_DIR, "Petra_CanvasApp_KEIN_FLOW.zip")
CANVAS_PATH   = "CanvasApps/petra_petra_5b88e_DocumentUri.msapp"

ZONES = '["E","F","H","I","A","B","C","D","T","G","P","W"]'
ONSTART = (
    'Set(gZoneMap,Table({zone:"E",idx:0},{zone:"F",idx:1},{zone:"H",idx:2},'
    '{zone:"I",idx:3},{zone:"A",idx:4},{zone:"B",idx:5},{zone:"C",idx:6},'
    '{zone:"D",idx:7},{zone:"T",idx:8},{zone:"G",idx:9},{zone:"P",idx:10},'
    '{zone:"W",idx:11}));ClearCollect(gTaxis,[{ID:1,FunkID:"Taxi 1",'
    'Position:"E",Capacity:8,Occupied:0,Active:true},{ID:2,FunkID:"Taxi 2",'
    'Position:"H",Capacity:8,Occupied:0,Active:true}]);Set(gSelectedZone,"E");'
    'Set(gPassengers,1);Set(gBestTaxi,Blank());Set(gETA,0);'
    'Set(gVonZone,"E");Set(gNachZone,"H");Set(gETAResult,0)'
)

# ── Minimal YAML (nur was Power Apps erwartet, kein OnStart im YAML) ─────────

APP_YAML = """\
App:
  Properties:
    Theme: =PowerAppsTheme
"""

EDITOR_YAML = """\
EditorState:
  ScreensOrder:
    - DispatchScreen
    - ETAScreen
    - TaxiStatusScreen
    - Screen1
"""

# Screen1 YAML unverändert
SCREEN1_YAML = """\
Screens:
  Screen1:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
"""

# ── Controls-JSON Hilfsfunktionen ─────────────────────────────────────────────

def ctrl_info(name, uid, template_id, template_name, template_ver,
              style, parent, rules, children=None, is_data=False):
    return {
        "Type": "ControlInfo",
        "Name": name,
        "HasDynamicProperties": False,
        "Template": {
            "Id": template_id,
            "Version": template_ver,
            "LastModifiedTimestamp": "0",
            "Name": template_name,
            "FirstParty": True,
            "IsPremiumPcfControl": False,
            "IsCustomGroupControlTemplate": False,
            "CustomGroupControlTemplateName": "",
            "IsComponentDefinition": False,
            "OverridableProperties": {}
        },
        "Index": uid,
        "PublishOrderIndex": uid,
        "VariantName": "",
        "LayoutName": "",
        "MetaDataIDKey": "",
        "PersistMetaDataIDKey": False,
        "IsFromScreenLayout": False,
        "StyleName": style,
        "Parent": parent,
        "IsDataControl": is_data,
        "AllowAccessToGlobals": True,
        "OptimizeForDevices": "Off",
        "IsGroupControl": False,
        "IsAutoGenerated": False,
        "Rules": rules,
        "ControlPropertyState": [r["Property"] for r in rules],
        "IsLocked": False,
        "ControlUniqueId": str(uid),
        "Children": children or []
    }


def rule(prop, cat, script):
    return {"Property": prop, "Category": cat,
            "InvariantScript": script, "RuleProviderType": "Unknown"}


def label(name, uid, parent, x, y, w, h, text, size=14,
          bold=False, color="RGBA(50,50,50,1)", fill="RGBA(0,0,0,0)",
          align="Align.Left", valign="VerticalAlign.Middle"):
    rules = [
        rule("X", "Design", str(x)),
        rule("Y", "Design", str(y)),
        rule("Width", "Design", str(w)),
        rule("Height", "Design", str(h)),
        rule("Text", "Data", text),
        rule("Size", "Design", str(size)),
        rule("Color", "Design", color),
        rule("Fill", "Design", fill),
        rule("Align", "Design", align),
        rule("VerticalAlign", "Design", valign),
    ]
    if bold:
        rules.append(rule("FontWeight", "Design", "FontWeight.Bold"))
    return ctrl_info(name, uid,
        "http://microsoft.com/appmagic/label", "label", "2.9.1",
        "defaultLabelStyle", parent, rules)


def button(name, uid, parent, x, y, w, h, text, on_select,
           color="RGBA(255,255,255,1)", fill="RGBA(0,70,127,1)"):
    rules = [
        rule("X", "Design", str(x)),
        rule("Y", "Design", str(y)),
        rule("Width", "Design", str(w)),
        rule("Height", "Design", str(h)),
        rule("Text", "Data", text),
        rule("Color", "Design", color),
        rule("Fill", "Design", fill),
        rule("OnSelect", "Behavior", on_select),
        rule("RadiusBottomLeft", "Design", "8"),
        rule("RadiusBottomRight", "Design", "8"),
        rule("RadiusTopLeft", "Design", "8"),
        rule("RadiusTopRight", "Design", "8"),
    ]
    return ctrl_info(name, uid,
        "http://microsoft.com/appmagic/button", "button", "2.4.1",
        "defaultButtonStyle", parent, rules)


def dropdown(name, uid, parent, x, y, w, h, items, on_change):
    rules = [
        rule("X", "Design", str(x)),
        rule("Y", "Design", str(y)),
        rule("Width", "Design", str(w)),
        rule("Height", "Design", str(h)),
        rule("Items", "Data", items),
        rule("OnChange", "Behavior", on_change),
    ]
    return ctrl_info(name, uid,
        "http://microsoft.com/appmagic/dropdown", "dropdown", "2.4.2",
        "defaultDropdownStyle", parent, rules)


def slider(name, uid, parent, x, y, w, h, min_v, max_v, on_change):
    rules = [
        rule("X", "Design", str(x)),
        rule("Y", "Design", str(y)),
        rule("Width", "Design", str(w)),
        rule("Height", "Design", str(h)),
        rule("Min", "Data", str(min_v)),
        rule("Max", "Data", str(max_v)),
        rule("OnChange", "Behavior", on_change),
    ]
    return ctrl_info(name, uid,
        "http://microsoft.com/appmagic/slider", "slider", "2.3.1",
        "defaultSliderStyle", parent, rules)


def screen_json(name, uid, index, children):
    top = {
        "TopParent": ctrl_info(
            name, uid,
            "http://microsoft.com/appmagic/screen", "screen", "1.0",
            "defaultScreenStyle", "",
            [
                rule("Fill", "Design", "RGBA(245,247,250,1)"),
                rule("ImagePosition", "Design", "ImagePosition.Fit"),
                rule("Height", "Design", "Max(App.Height, App.MinScreenHeight)"),
                rule("Width", "Design", "Max(App.Width, App.MinScreenWidth)"),
                rule("Size", "Design", "1 + CountRows(App.SizeBreakpoints) - CountIf(App.SizeBreakpoints, Value >= Self.Width)"),
                rule("Orientation", "Design", "If(Self.Width < Self.Height, Layout.Vertical, Layout.Horizontal)"),
                rule("LoadingSpinner", "Design", "LoadingSpinner.None"),
                rule("LoadingSpinnerColor", "Design", "RGBA(56,96,178,1)"),
            ],
            children
        )
    }
    # Fix parent names
    top["TopParent"]["IsDataControl"] = False
    return top


# ── Screen-Definitionen ───────────────────────────────────────────────────────

DISPATCH_ONSELECT = (
    "Set(gPickupIdx,LookUp(gZoneMap,zone=ZoneDD.Selected.Value,idx));"
    "ClearCollect(colScored,AddColumns(Filter(gTaxis,(Capacity-Occupied)>=Round(PSld.Value,0)),"
    "\"Score\",Abs(LookUp(gZoneMap,zone=Position,idx)-gPickupIdx),"
    "\"FreiePlaetze\",Capacity-Occupied));"
    "Set(gBestTaxi,First(Sort(colScored,Score,SortOrder.Ascending)));"
    "If(!IsBlank(gBestTaxi),Set(gETA,Round(Abs(LookUp(gZoneMap,zone=gBestTaxi.Position,idx)-gPickupIdx)*0.8/30*60,0)))"
)

ETA_ONSELECT = (
    "Set(gETAResult,Round(Abs(LookUp(gZoneMap,zone=VonDD.Selected.Value,idx)"
    "-LookUp(gZoneMap,zone=NachDD.Selected.Value,idx))*0.8/30*60,0))"
)

def build_dispatch(n):
    """n = Basis-UID für Controls auf diesem Screen"""
    sc = "DispatchScreen"
    nav_fill  = "RGBA(70,130,180,1)"
    return [
        label("HeaderLbl", n, sc, 0, 0, 1366, 80,
              '"PETRA \u2013 Taxi Dispatch"', 22, True,
              "RGBA(255,255,255,1)", "RGBA(0,70,127,1)", "Align.Center"),
        label("ZoneLbl", n+1, sc, 40, 95, 300, 36,
              '"Abholzone:"', 14, True),
        dropdown("ZoneDD", n+2, sc, 40, 135, 300, 44, ZONES,
                 'Set(gSelectedZone,ZoneDD.Selected.Value)'),
        label("PaxLbl", n+3, sc, 40, 200, 380, 36,
              '"Passagiere: "&Text(Round(PSld.Value,0))', 14, True),
        slider("PSld", n+4, sc, 40, 242, 300, 44, 1, 8,
               'Set(gPassengers,Round(PSld.Value,0))'),
        button("FindBtn", n+5, sc, 40, 310, 300, 52,
               '"Bestes Taxi finden"', DISPATCH_ONSELECT),
        label("ResultLbl", n+6, sc, 40, 380, 800, 140,
              'If(IsBlank(gBestTaxi),"Kein Taxi verf\u00fcgbar.",'
              '"Taxi: "&gBestTaxi.FunkID&" | Zone "&gBestTaxi.Position'
              '&" | ETA: "&Text(gETA)&" Min | Pl\u00e4tze: "&Text(gBestTaxi.FreiePlaetze))',
              16, False, "RGBA(0,70,127,1)", "RGBA(255,255,255,1)"),
        button("NavETA", n+7, sc, 40, 550, 200, 44,
               '"ETA"', 'Navigate(ETAScreen,ScreenTransition.Fade)',
               fill=nav_fill),
        button("NavStatus", n+8, sc, 260, 550, 200, 44,
               '"Taxi-Status"', 'Navigate(TaxiStatusScreen,ScreenTransition.Fade)',
               fill="RGBA(100,100,180,1)"),
    ]


def build_eta(n):
    sc = "ETAScreen"
    return [
        label("ETAHeaderLbl", n, sc, 0, 0, 1366, 80,
              '"PETRA \u2013 ETA Berechnung"', 22, True,
              "RGBA(255,255,255,1)", "RGBA(0,70,127,1)", "Align.Center"),
        label("VonLbl", n+1, sc, 40, 100, 200, 36, '"Von Zone:"', 14, True),
        dropdown("VonDD", n+2, sc, 40, 140, 300, 44, ZONES,
                 'Set(gVonZone,VonDD.Selected.Value)'),
        label("NachLbl", n+3, sc, 40, 205, 200, 36, '"Nach Zone:"', 14, True),
        dropdown("NachDD", n+4, sc, 40, 245, 300, 44, ZONES,
                 'Set(gNachZone,NachDD.Selected.Value)'),
        button("ETABtn", n+5, sc, 40, 315, 300, 52,
               '"ETA Berechnen"', ETA_ONSELECT),
        label("ETAResultLbl", n+6, sc, 40, 390, 800, 80,
              '"Zone "&VonDD.Selected.Value&" \u2192 "&NachDD.Selected.Value'
              '&" | "&Text(gETAResult)&" Minuten"',
              20, True, "RGBA(0,70,127,1)", "RGBA(255,255,255,1)"),
        button("ETABack", n+7, sc, 40, 510, 200, 44,
               '"Dispatch"', 'Navigate(DispatchScreen,ScreenTransition.Fade)',
               fill="RGBA(100,100,180,1)"),
        button("ETANavStatus", n+8, sc, 260, 510, 200, 44,
               '"Taxi-Status"', 'Navigate(TaxiStatusScreen,ScreenTransition.Fade)',
               fill="RGBA(70,130,180,1)"),
    ]


def build_status(n):
    sc = "TaxiStatusScreen"
    return [
        label("StHeaderLbl", n, sc, 0, 0, 1366, 80,
              '"PETRA \u2013 Taxi Status"', 22, True,
              "RGBA(255,255,255,1)", "RGBA(0,70,127,1)", "Align.Center"),
        label("StCountLbl", n+1, sc, 40, 100, 600, 32,
              '"Aktive Taxis: "&Text(CountRows(Filter(gTaxis,Active)))'
              '&" / "&Text(CountRows(gTaxis))',
              14, True),
        # Taxi 1 card
        label("T1Lbl", n+2, sc, 40, 155, 600, 30,
              '"Taxi 1 | Zone E | Freie Pl\u00e4tze: 8 | Aktiv"',
              15, False, "RGBA(0,140,60,1)", "RGBA(255,255,255,1)"),
        # Taxi 2 card
        label("T2Lbl", n+3, sc, 40, 205, 600, 30,
              '"Taxi 2 | Zone H | Freie Pl\u00e4tze: 8 | Aktiv"',
              15, False, "RGBA(0,140,60,1)", "RGBA(255,255,255,1)"),
        label("StInfoLbl", n+4, sc, 40, 260, 700, 28,
              '"(Demo-Daten – im Live-Betrieb via SharePoint verbunden)"',
              12, False, "RGBA(150,150,150,1)"),
        button("StBack", n+5, sc, 40, 620, 200, 44,
               '"Dispatch"', 'Navigate(DispatchScreen,ScreenTransition.Fade)',
               fill="RGBA(100,100,180,1)"),
        button("StNavETA", n+6, sc, 260, 620, 200, 44,
               '"ETA"', 'Navigate(ETAScreen,ScreenTransition.Fade)',
               fill="RGBA(70,130,180,1)"),
    ]


# ── App-Control JSON (Controls\1.json) mit OnStart ───────────────────────────

def build_app_json(original_app_json_bytes):
    """Nimm original Controls/1.json und füge OnStart in App-Rules ein."""
    original = json.loads(original_app_json_bytes.decode("utf-8"))
    # OnStart in Rules des App-Controls einfügen
    app_rules = original["TopParent"]["Rules"]
    # Entferne altes OnStart falls vorhanden
    app_rules = [r for r in app_rules if r["Property"] != "OnStart"]
    app_rules.append({
        "Property": "OnStart",
        "Category": "Behavior",
        "InvariantScript": ONSTART,
        "RuleProviderType": "Unknown"
    })
    original["TopParent"]["Rules"] = app_rules
    prop_state = original["TopParent"].get("ControlPropertyState", [])
    if "OnStart" not in prop_state:
        prop_state.append("OnStart")
    original["TopParent"]["ControlPropertyState"] = prop_state
    return json.dumps(original, indent=2).encode("utf-8")


# ── Packing ───────────────────────────────────────────────────────────────────

def build():
    print(f"Quelle:  {SOLUTION_IN}")
    print(f"Ausgabe: {SOLUTION_OUT}\n")

    with zipfile.ZipFile(SOLUTION_IN) as sol:
        orig_msapp = sol.read(CANVAS_PATH)

    new_msapp_buf = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(orig_msapp)) as orig:
        orig_app_json = None
        for item in orig.infolist():
            if item.filename.replace("\\", "/") == "Controls/1.json":
                orig_app_json = orig.read(item.filename)
                break

        with zipfile.ZipFile(new_msapp_buf, "w", zipfile.ZIP_DEFLATED) as new:
            for item in orig.infolist():
                fn_norm = item.filename.replace("\\", "/")

                if fn_norm == "Controls/1.json":
                    data = build_app_json(orig_app_json)
                    new.writestr(item, data)
                    print(f"  ✓ {item.filename}  (OnStart hinzugefügt)")

                elif fn_norm == "Src/App.pa.yaml":
                    new.writestr(item, APP_YAML.encode("utf-8"))
                    print(f"  ✓ {item.filename}  (minimal)")

                elif fn_norm == "Src/_EditorState.pa.yaml":
                    new.writestr(item, EDITOR_YAML.encode("utf-8"))
                    print(f"  ✓ {item.filename}  (Screens aktualisiert)")

                elif fn_norm == "Src/Screen1.pa.yaml":
                    new.writestr(item, SCREEN1_YAML.encode("utf-8"))
                    print(f"  ✓ {item.filename}  (unverändert)")

                else:
                    new.writestr(item, orig.read(item.filename))
                    print(f"  ✓ {item.filename}")

            # Neue Screens als Controls-JSON (Backslash-Pfade)
            screens = [
                ("Controls\\5.json", "DispatchScreen", 5, 1, build_dispatch(50)),
                ("Controls\\6.json", "ETAScreen",      6, 2, build_eta(100)),
                ("Controls\\7.json", "TaxiStatusScreen", 7, 3, build_status(150)),
            ]
            for path, name, uid, idx, children in screens:
                data = json.dumps(screen_json(name, uid, idx, children), indent=2)
                new.writestr(path, data.encode("utf-8"))
                print(f"  ✓ {path}  ({name}, {len(children)} Controls)")

    msapp_bytes = new_msapp_buf.getvalue()
    print(f"\nmsapp: {len(msapp_bytes):,} Bytes")

    out_buf = io.BytesIO()
    with zipfile.ZipFile(SOLUTION_IN) as sol:
        with zipfile.ZipFile(out_buf, "w", zipfile.ZIP_DEFLATED) as out:
            for item in sol.infolist():
                if item.filename == CANVAS_PATH:
                    out.writestr(item, msapp_bytes)
                    print(f"  ✓ {item.filename}  (ersetzt)")
                else:
                    out.writestr(item, sol.read(item.filename))

    out_buf.seek(0)
    with open(SOLUTION_OUT, "wb") as f:
        f.write(out_buf.read())

    kb = os.path.getsize(SOLUTION_OUT) // 1024
    print(f"\n✅ Fertig: {SOLUTION_OUT}  ({kb} KB)")
    print("\nImport: make.powerapps.com → Solutions → Petra → Importieren")
    print("→ Datei: Petra_CanvasApp_KEIN_FLOW.zip")


if __name__ == "__main__":
    build()
