#!/usr/bin/env python3
"""
Build script for the Petra Canvas App (.msapp)
Generates Controls JSON for 3 screens and packs a new solution ZIP.
"""

import json
import os
import zipfile
import io
import shutil

BUILD_DIR = os.path.dirname(os.path.abspath(__file__)) + "/msapp-build"
SOLUTION_IN = os.path.dirname(os.path.abspath(__file__)) + "/powerapps-solution/Petra_1_0_0_0.zip"
SOLUTION_OUT = os.path.dirname(os.path.abspath(__file__)) + "/powerapps-solution/Petra_1_0_0_1.zip"
MSAPP_NAME = "CanvasApps/petra_petra_5b88e_DocumentUri.msapp"


def make_screen_control(name, unique_id, title=None, index=0):
    """Return the TopParent JSON structure for a Screen."""
    rules = [
        {"Property": "Fill", "Category": "Design", "InvariantScript": "RGBA(245, 247, 250, 1)", "RuleProviderType": "Unknown"},
        {"Property": "ImagePosition", "Category": "Design", "InvariantScript": "ImagePosition.Fit", "RuleProviderType": "Unknown"},
        {"Property": "Height", "Category": "Design", "InvariantScript": "Max(App.Height, App.MinScreenHeight)", "RuleProviderType": "Unknown"},
        {"Property": "Width", "Category": "Design", "InvariantScript": "Max(App.Width, App.MinScreenWidth)", "RuleProviderType": "Unknown"},
        {"Property": "Size", "Category": "Design", "InvariantScript": "1 + CountRows(App.SizeBreakpoints) - CountIf(App.SizeBreakpoints, Value >= Self.Width)", "RuleProviderType": "Unknown"},
        {"Property": "Orientation", "Category": "Design", "InvariantScript": "If(Self.Width < Self.Height, Layout.Vertical, Layout.Horizontal)", "RuleProviderType": "Unknown"},
        {"Property": "LoadingSpinner", "Category": "Design", "InvariantScript": "LoadingSpinner.None", "RuleProviderType": "Unknown"},
        {"Property": "LoadingSpinnerColor", "Category": "Design", "InvariantScript": "RGBA(56, 96, 178, 1)", "RuleProviderType": "Unknown"},
    ]
    if title:
        rules.append({
            "Property": "AccessibleLabel",
            "Category": "Accessibility",
            "InvariantScript": f"\"{title}\"",
            "RuleProviderType": "Unknown"
        })

    return {
        "TopParent": {
            "Type": "ControlInfo",
            "Name": name,
            "Template": {
                "Id": "http://microsoft.com/appmagic/screen",
                "Version": "1.0",
                "LastModifiedTimestamp": "0",
                "Name": "screen",
                "FirstParty": True,
                "IsPremiumPcfControl": False,
                "IsCustomGroupControlTemplate": False,
                "CustomGroupControlTemplateName": "",
                "IsComponentDefinition": False,
                "OverridableProperties": {}
            },
            "Index": index,
            "PublishOrderIndex": index,
            "VariantName": "",
            "LayoutName": "",
            "MetaDataIDKey": "",
            "PersistMetaDataIDKey": False,
            "IsFromScreenLayout": False,
            "StyleName": "defaultScreenStyle",
            "Parent": "",
            "IsDataControl": False,
            "AllowAccessToGlobals": True,
            "OptimizeForDevices": "Off",
            "IsGroupControl": False,
            "IsAutoGenerated": False,
            "Rules": rules,
            "ControlPropertyState": ["Fill", "ImagePosition", "Height", "Width", "Size", "Orientation", "LoadingSpinner", "LoadingSpinnerColor"],
            "IsLocked": False,
            "ControlUniqueId": str(unique_id),
            "Children": []
        }
    }


def update_editor_state():
    """Rewrite _EditorState.pa.yaml with the 3 new screens."""
    content = """# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
EditorState:
  ScreensOrder:
    - DispatchScreen
    - ETAScreen
    - TaxiStatusScreen
"""
    with open(os.path.join(BUILD_DIR, "Src", "_EditorState.pa.yaml"), "w", encoding="utf-8") as f:
        f.write(content)
    print("Updated _EditorState.pa.yaml")


def update_header():
    """Update Header.json with current timestamp."""
    header = {
        "DocVersion": "1.348",
        "MinVersionToLoad": "1.348",
        "MSAppStructureVersion": "2.4.0",
        "LastSavedDateTimeUTC": "03/01/2026 12:00:00",
        "AnalysisOptions": {
            "DataflowAnalysisEnabled": True,
            "DataflowAnalysisFlagStateToggledByUser": False
        }
    }
    with open(os.path.join(BUILD_DIR, "Header.json"), "w", encoding="utf-8") as f:
        json.dump(header, f, separators=(",", ":"))
    print("Updated Header.json")


def write_screen_controls():
    """Write Controls/*.json for each of the 3 screens."""
    screens = [
        ("DispatchScreen", 10, "Dispatch"),
        ("ETAScreen", 11, "ETA"),
        ("TaxiStatusScreen", 12, "Taxi Status"),
    ]
    for name, uid, title in screens:
        ctrl = make_screen_control(name, uid, title)
        path = os.path.join(BUILD_DIR, "Controls", f"{uid}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(ctrl, f, indent=2)
        print(f"Wrote Controls/{uid}.json for {name}")


def delete_old_screen1_files():
    """Remove Screen1 references that no longer apply."""
    old_yaml = os.path.join(BUILD_DIR, "Src", "Screen1.pa.yaml")
    if os.path.exists(old_yaml):
        os.remove(old_yaml)
        print("Removed Src/Screen1.pa.yaml")
    old_ctrl = os.path.join(BUILD_DIR, "Controls", "4.json")
    if os.path.exists(old_ctrl):
        os.remove(old_ctrl)
        print("Removed Controls/4.json (old Screen1)")


def pack_msapp():
    """Pack the msapp-build directory into a .msapp ZIP."""
    msapp_buf = io.BytesIO()
    with zipfile.ZipFile(msapp_buf, "w", zipfile.ZIP_DEFLATED) as zout:
        for root, dirs, files in os.walk(BUILD_DIR):
            for fname in files:
                full_path = os.path.join(root, fname)
                arcname = os.path.relpath(full_path, BUILD_DIR)
                zout.write(full_path, arcname)
                print(f"  Packed: {arcname}")
    msapp_buf.seek(0)
    return msapp_buf.read()


def pack_solution(msapp_bytes):
    """Create a new solution ZIP, replacing the tablet .msapp."""
    with zipfile.ZipFile(SOLUTION_IN, "r") as zin:
        all_names = zin.namelist()

    out_buf = io.BytesIO()
    with zipfile.ZipFile(SOLUTION_IN, "r") as zin:
        with zipfile.ZipFile(out_buf, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if item.filename == MSAPP_NAME:
                    zout.writestr(item, msapp_bytes)
                    print(f"  Replaced {MSAPP_NAME}")
                else:
                    zout.writestr(item, zin.read(item.filename))
                    print(f"  Kept {item.filename}")

    out_buf.seek(0)
    with open(SOLUTION_OUT, "wb") as f:
        f.write(out_buf.read())
    print(f"\nWrote solution: {SOLUTION_OUT}")


if __name__ == "__main__":
    print("=== Building Petra Canvas App ===\n")
    delete_old_screen1_files()
    update_editor_state()
    update_header()
    write_screen_controls()
    print("\n=== Packing .msapp ===")
    msapp_bytes = pack_msapp()
    print(f"\nmsapp size: {len(msapp_bytes):,} bytes")
    print("\n=== Packing solution ZIP ===")
    pack_solution(msapp_bytes)
    print("\n✅ Done! Import powerapps-solution/Petra_1_0_0_1.zip into Power Platform.")
